[pt] Added rule ID:FICAR_PARADO_TEMPO_ESTAGNAR
languagetool-org/languagetool pull request #10054
Opened 2024-01-07 07:04 UTC by marcoagpinto

Heya, @susanaboatto and @p-goulart 

I have just created this rule.

It had zero hits in 900 000 sentences.

Follow the discussion here:
https://github.com/languagetool-org/languagetool/issues/10053

Thanks!

2024-01-09 15:10 UTC, susanaboatto approved these changes

2024-01-09 15:28 UTC, susanaboatto commented on languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
> +            <message>Num contexto formal/académico, é preferível escrever &quot;estagnar&quot;.</message>
This message also needs to be dialect-neutral

2024-01-09 15:29 UTC, susanaboatto requested changes
Rule looks ok, just need a minor change in the message so that it works in all dialects.

2024-01-11 13:00 UTC, p-goulart approved these changes

2024-01-11 13:02 UTC, merged

2024-01-11 13:03 UTC, marcoagpinto commented
Thank you, @p-goulart 

❤️ ❤️ ❤️ ❤️ ❤️