[LO extension / Standalone] add the possibility to define more than o…
languagetool-org/languagetool pull request #10542
Opened 2024-04-25 16:40 UTC by FredKruse

The change creates the ability to define more than one custom option per rule.
All existing rules with custom options have been adjusted. The options panel has been expanded accordingly.
The API and the HTTP server (ConfigurationInfo) have been adapted. Upward and downward compatibility between versions lower than 6.5 and higher than 6.4 was ensured.
A second option was added for the GermanFillerWordsRule as a test case.
All changes were tested.
To-do: Some more rules should be expanded to include additional options.
A merge can be performed.

2024-04-25 17:36 UTC, danielnaber requested changes

2024-04-25 17:36 UTC, danielnaber commented on languagetool-gui-commons/src/main/java/org/languagetool/gui/Configuration.java
> +            if (c == 's') {
A comment with examples would be nice here

2024-04-25 17:36 UTC, danielnaber commented on languagetool-core/src/main/java/org/languagetool/rules/RuleOption.java
> +
empty lines

2024-04-25 17:36 UTC, danielnaber commented on languagetool-office-extension/src/main/java/org/languagetool/openoffice/LORemoteLanguageTool.java
> +          if (o instanceof Integer) {
Is this code duplicated from above? Can we avoid the duplication?

2024-04-25 17:36 UTC, danielnaber commented on languagetool-office-extension/src/main/java/org/languagetool/openoffice/LORemoteLanguageTool.java
> +            minConfigurableValue = (int) rOptions.get(i).get("minConfigurableValue");
`minConfigurableValue` etc. should probably be a constant, as it is used several times

2024-04-25 17:36 UTC, danielnaber commented on languagetool-office-extension/src/main/java/org/languagetool/openoffice/LORemoteLanguageTool.java
> +        for (int i = 0; i < rOptions.size(); i++) {
This code is duplicated?

2024-04-25 17:36 UTC, danielnaber commented on languagetool-server/src/main/java/org/languagetool/server/TextChecker.java
> +          objects[i] = Integer.parseInt(values[i]);
This is duplicated?

2024-04-25 17:37 UTC, danielnaber commented
@fabrichter Maybe you can quickly check whether the change in `UserConfig` is harmless?

2024-04-26 10:58 UTC, FredKruse commented
The requested changes was done

2024-04-26 12:00 UTC, fabrichter commented
@danielnaber 
For UserConfig, the change to an Array probably breaks `.equals` and thus pipeline caching because equals on arrays checks for reference equality. But this most likely isn't relevant in practice, since for the use case where pipeline caching is enabled, configurableRuleValues is always empty. So I think we don't need to change this, but a comment about it in `.equals` would be good to add.

I would also add a better getter for the configuration values like this:
```java

  public <T> T getConfigValueByID(String ruleID, int index, Class<T> clazz, T defaultValue) {
    Object value = configurableRuleValues.get(ruleID);
    if (value == null) return defaultValue;

    if (index >= value.length) return defaultValue;
    if (!clazz.isInstance(value[index])) return defaultValue;

    return (T) value;
  }

```

This should be used instead of the existing manual accesses and checks to inner values of `configurableRuleValues`, as the checks are repetitive and not done consistently as-is.

2024-04-27 11:17 UTC, FredKruse commented
The requested changes from @fabrichter and @danielnaber was done.

2024-04-29 08:20 UTC, merged