[en] BASIC START "worked here since 2002"
languagetool-org/languagetool pull request #4673
Opened 2021-03-25 06:27 UTC by AzadehSafakish

Just a very basic start on the “he worked here since 2002” issue. Obviously, there’s different tenses that you could use depending on the context that follows this phrase; that’s its own box of worms. Does not include the verb “to be,” I’ll add that on later. The logic is:

WORK HERE SINCE [DATE]  (e.g. 2002)

I work here since 2002 	—>	I have been working here since 2002

I worked here since 2002 —> 	I have worked here since 2002

Also inflected for 3rd person.

Next I want to tackle the phrase WORK HERE FOR [SPAN OF TIME e.g. 3 years]. Tenses are a bit different for that one…

2021-03-25 16:36 UTC, udomai requested changes

2021-03-25 16:36 UTC, udomai commented on languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
> +        <rulegroup id="WORK_HERE_SINCE_DATE" name="present/past to progressive/perfect">
Always remember `default="temp_off"`

2021-03-25 16:37 UTC, udomai commented
You can leave the "for" contexts for another time :)

2021-03-27 01:51 UTC, AzadehSafakish commented
Pulled a cleaner, updated version of this rule :)

2021-03-27 01:51 UTC, closed without merging