[en] common VB/VBN confusions not found
languagetool-org/languagetool pull request #4680
Opened 2021-03-26 11:22 UTC by AzadehSafakish

New rule group which takes care of phrases like the following (all of which are not detected by LT):

PRESENT
Am I go the right way? -> going
Are his friends leave today? -> leaving
Isn't he visit his mom? -> visiting
Aren't his friends see the show -> seeing

PAST
Were they send via WhatsApp? → sent
Weren't those houses build with the help of a construction company? → built
Weren't they tell over the phone -> told

And so on...

2021-03-26 16:04 UTC, udomai requested changes

2021-03-26 16:18 UTC, udomai commented on languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
> +                <example> [Typo] Is it suppose to look like that?</example>
Is [Typo] intended as a comment? In that case, don't write it like that, examples are very literal. You can append it as a comment directly after `</example><!-- Typo to be found be other rule -->`

2021-03-26 16:35 UTC, udomai commented
The first subrule causes false alarms that can be spotted in the rule editor. The way I tested it was: Copy the first subrule into the rule editor. Take all the general antipatterns (APs), i.e. the ones that appear before the first `<rule>`, and copy them into the rule in the rule editor.

Here are some of the sentences the rule editor finds:

<details>
    <summary>Excerpt from the rule editor results</summary>
    
Here is one **option** to restart your workers. → optioning
What I can say is I **have** been unable to trait the few troops I use. → having
Here is one **example**: → exampling

</details>

I've run the entire rulegroup over the nightly diff corpus (first 700,000 sentences), and here is what it found:

[BE_PART_AGREEMENT_SSC_results.txt](https://github.com/languagetool-org/languagetool/files/6213133/BE_PART_AGREEMENT_SSC_results.txt)

There are many false positives. This is a normal step in rule developing: You check for false positives, and you adjust the pattern, or write antipatterns (and exceptions) until it works :)

Please refine the rulegroup and let me know here or on Slack when you're done.

2021-03-27 09:30 UTC, AzadehSafakish commented
updated

2021-03-30 15:45 UTC, udomai commented
Updated here: https://github.com/languagetool-org/languagetool/pull/4691

2021-03-30 15:45 UTC, closed without merging