[en] UPDATED common VB/VBN confusions not found
languagetool-org/languagetool pull request #4691
Opened 2021-03-27 09:29 UTC by AzadehSafakish

Refined antipatterns and exceptions. 

The sentence source checker only catches 2 phrases out of the first 850,00, neither of which are actual false-positives.

2021-03-30 16:08 UTC, udomai requested changes

2021-04-05 03:51 UTC, AzadehSafakish commented
Still chewing on this one; there's a LOT of work that needs to be done.

I'll try my best to have it finished by Tuesday. For now, I'm converting it to a draft.

#4674

2021-04-06 03:02 UTC, AzadehSafakish commented
Rules 1-6 out of 8 don't trigger any FPs, however rule 7 is a different story. I'll probably have to make some adjustments to the antipatterns, and then test rules 1-6 again. But, almost finished!

2021-04-08 09:44 UTC, AzadehSafakish commented
Finished, marking as ready for review.

2021-04-08 14:20 UTC, udomai approved these changes

2021-04-08 14:30 UTC, merged