Rm5 additionnal rules on comma sentence start 1
languagetool-org/languagetool pull request #4804
Opened 2021-04-12 13:37 UTC by remymartinDev

2021-04-22 10:41 UTC, udomai commented
Note to self:

- FPs to eliminate
- put into a rulegroup VIRGULE_DEBUT_DE_PHRASE_2 (to see statistics)

2021-04-22 12:35 UTC, udomai requested changes

2021-04-22 12:35 UTC, udomai commented on languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
> +            <rule default="temp_off">
Just to resume today's call:

- [ ] please create a rulegroup named `VIRGULE_DEBUT_DE_PHRASE_2` with these rules.
→ this allows us to look at the statistics separately. Later, we will merge it with the original rule.

- [ ] please set the rulegroup `temp_off` and erase the `default="temp_off"` from the subrules

- [ ] please remove the FPs, e.g. `!`, `que` etc.

… and let me know in a comment when you're done, so we get this rule rolling 😄

2021-04-22 12:44 UTC, remymartinDev commented
-> 6 rules grouped in a new rulegroup
-> added [!] exception
-> also added exceptions in some rules (ex: "Certainement pas !" "Sans aucun doute possible.", etc...)

2021-04-22 13:00 UTC, udomai commented on languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
> +                    <token regexp="yes">[^,‘’–)\[—!."\/;\]\|:(\…'«»“”-]+</token>
These collections are missing the `\?`, I'd say

2021-04-23 13:08 UTC, udomai approved these changes

2021-04-23 13:08 UTC, merged