[en] draft FINAL_ADVERB_COMMA
languagetool-org/languagetool pull request #4816
Opened 2021-04-13 09:10 UTC by AzadehSafakish

Not finished yet... there's another adverb I want to add + FPs to iron out.

Leaving off here for tonight.

2021-04-14 14:47 UTC, udomai requested changes

2021-04-14 14:47 UTC, udomai commented on languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
> +        <rule id="FINAL_ADVERB_COMMA" tags="picky" name="comma before ending sentence with adverb" default="temp_off">
Let's try it without "picky"!

2021-04-15 07:10 UTC, AzadehSafakish commented on languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
> +        <rule id="FINAL_ADVERB_COMMA" tags="picky" name="comma before ending sentence with adverb" default="temp_off">
Removed the tag

2021-04-15 15:32 UTC, udomai requested changes

2021-04-15 15:32 UTC, udomai commented on languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml
> +                <token regexp="yes">actually|allegedly|apparently|certainly|fortunately|honestly|hopefully|however|maybe|obviously|perchance|perhaps|probably|surely|unfortunately</token>
One last thing: could you place a `<marker>` only around the adverb, please? The suggestion will then be, e.g. `, maybe`. Making the rule only match the key word prevents overlapping matches.

2021-04-15 23:51 UTC, closed without merging