[fr] VIRGULE_DEBUT_DE_PHRASE_3
languagetool-org/languagetool pull request #4939
Opened 2021-04-30 14:48 UTC by remymartinDev

this is a first shot
I'm sure that the 3 rules are factorisable so I'll rework the rulegroup to optimize the code

2021-05-03 14:19 UTC, udomai requested changes

2021-05-03 14:19 UTC, udomai commented on languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
> +                            <exception postag="A.*" postag_regexp="yes" scope="next"/>
You can tidy this up:

`<exception postag="[PNDZJA].*|C coor.*|R pers obj.*" postag_regexp="yes" scope="next"/>`.

Or you can go right ahead and say what you want the next token to be (`R pers suj`?). Do you really want to exclude all the others?

"Bonjour mon ami !" seems to be missing a comma, as does "Bonne nuit camarade !"

2021-05-03 14:19 UTC, udomai commented on languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
> +                <example>Bonne nuit toutes et tous. (A)</example>
This kind of technical remark cannot be included in an example (examples will be visible to users at some point, so we cannot put any technical stuff in there). If you want to include a comment, you can do that in a `<!-- … -->` after the example.

2021-05-04 15:24 UTC, remymartinDev commented
I have to work more on this, because of N Z D, to find a way to make a difference between : 
- Bonjour, Jean.
- Bonjour Jean, je répond à ton email [...]

2021-05-14 10:10 UTC, udomai requested changes

2021-05-14 10:10 UTC, udomai commented on languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
> +                    <token postag=".*" postag_regexp="yes" min="0" max ="6"/>
`max ="6"` → `max="6"`

2021-05-14 10:11 UTC, udomai requested changes

2021-05-14 10:11 UTC, udomai commented on languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
> +                    <token postag=".*" postag_regexp="yes" min="0" max ="6"/>
`postag=".*" postag_regexp="yes"` → tu peux supprimer cela

2021-05-14 10:13 UTC, udomai requested changes

2021-05-14 10:13 UTC, udomai commented on languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
> +                    <token min="0" max ="6"/>
`max ="6"` → `max="6"`

2021-05-20 11:07 UTC, merged