[fr] useless anglicism + transfer picky tags in proper category
languagetool-org/languagetool pull request #5411
Opened 2021-07-27 07:27 UTC by remymartinDev

2021-07-27 16:15 UTC, udomai requested changes

2021-07-27 16:15 UTC, udomai commented on languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml
> +            <suggestion>affecter</suggestion>
Well spotted, but this rule has more problems: it takes any form of "assigner", but it always only gives "affecter" as a suggestion. Can be resolved with

```xml
<suggestion><match no="1" postag="V.*" postag_regexp="yes">affecter</match></suggestion>
```

to give "affecter" the same form that "assigner" has

2021-07-27 16:15 UTC, udomai commented
From which category to which other category did you move these?

2021-07-28 07:11 UTC, remymartinDev commented
> From which category to which other category did you move these?

Indeed, I should have mentioned it. There are 2 "Anglicism" categories : 
⇾ CAT_ANGLICISMES
⇾ CAT_ANGLICISMES_PICKY

all the rules found in CAT_ANGLICISMES with the tag `tags="picky"` have been moved to CAT_ANGLICISMES_PICKY

2021-08-05 08:43 UTC, merged