[de] KLAUEN_STIL
languagetool-org/languagetool pull request #6376
Opened 2022-02-25 14:05 UTC by St-ac-y

2022-02-28 15:23 UTC, udomai requested changes

2022-02-28 15:24 UTC, tiff commented
"Klauen" kann auch als Nomen verwendet werden: 
Plural von "Klaue" https://de.wiktionary.org/wiki/Klaue

2022-03-02 08:57 UTC, udomai requested changes

2022-03-02 11:09 UTC, udomai requested changes

2022-03-02 11:09 UTC, udomai commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +            <suggestion><match no="1" postag="VER.*" postag_regexp="yes">stehlen</match></suggestion>
`<match no="1" postag="(^VER:.*)(SFT$)? postag_regexp="yes" postag_replace="$1.*">stehlen</match>`

2022-03-04 10:15 UTC, udomai commented
Maybe later

2022-03-04 10:15 UTC, closed without merging