[de] HAUPTPROTAGONIST
languagetool-org/languagetool pull request #6386
Opened 2022-02-28 12:54 UTC by St-ac-y

2022-02-28 15:26 UTC, tiff commented
Hier muss man aufpassen, da die Kongruenz kaputtgehen könnte.
> Der Hauptprotagonist

Kann nicht einfach durch "Hauptfigur" ersetzt werden (die Hauptfigur).

2022-02-28 15:42 UTC, udomai requested changes

2022-02-28 15:42 UTC, udomai commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +            <example correction="Protagonist|Hauptfigur|Hauptcharakter">Die <marker>Hauptprotagonisten</marker> verlieren den Kampf um das goldene Zepter.</example>
Am besten einfach "Hauptfigur" rausnehmen

2022-03-02 11:12 UTC, udomai requested changes

2022-03-02 11:12 UTC, udomai commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +                <token inflected="yes">Hauptprotagonist</token>
Hier werden alle Formen von "Hauptprotagonist" zugelassen.

Problem 1: Ist das überhaupt getaggt?
Problem 2: Angenommen, da steht "Hauptprotagonisten", muss die Suggestion dynamisch gemacht werden.

2022-03-07 11:43 UTC, St-ac-y commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +                <token inflected="yes">Hauptprotagonist</token>
@udomai ja, ist getaggt. Habe das Problem mit zwei Rules gelöst (Sgl. und Pl.)
Falls es keine Verbesserungen gibt, kann gemerged werden.

2022-03-07 15:37 UTC, udomai requested changes

2022-03-07 15:37 UTC, udomai commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +            <message>Tautologie: Protagonisten sind bereis Hauptfiguren.</message>
Die Message muss nur noch leicht verändert werden: Das Wort "Tautologie" sagt den meisten Menschen ungefähr so viel wie "Pleonasmus". Tippfehler: "bereis".

"Da Protagonisten bereits Hauptfiguren sind, kann dieses Wort gedoppelt wirken." (oder so)

2022-03-07 15:46 UTC, St-ac-y commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +            <message>Tautologie: Protagonisten sind bereis Hauptfiguren.</message>
@udomai 
erledigt

2022-03-08 13:12 UTC, merged