[de] HANDELN_UEBER
languagetool-org/languagetool pull request #6400
Opened 2022-03-02 14:36 UTC by St-ac-y

2022-03-03 17:16 UTC, udomai requested changes

2022-03-03 17:16 UTC, udomai commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +                <token min="0" skip="-1"/>
siehe Kommentare in anderen Commits. `skip="-1"` kommt in das Token, nach dem beliebig viele weitere Token stehen können.

2022-03-07 11:47 UTC, St-ac-y commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +            <message>Das Verb 'handeln', im Sinne von 'es geht um' (ein Thema), verlangt die Präposition 'von'.</message>
@udomai alles erledigt und könnte gemerged werden.

2022-03-07 15:51 UTC, udomai approved these changes

2022-03-08 14:11 UTC, udomai commented
Diese Regel hat krasse FPs im Rule Editor. Sowas darf uns nicht durch die Lappen gehen.

> Das Handeln oder Verkaufen von Eiern im Forum oder über das Forum ist ebenfalls nicht gestattet.
> Georgios Kipouros vom European Youth Forum appellierte dringlich, jetzt endlich zu handeln und nicht weiter nur über Onlinesicherheit von Kindern und Jugendlichen zu reden.

2022-03-15 10:13 UTC, St-ac-y commented
> Diese Regel hat krasse FPs im Rule Editor. Sowas darf uns nicht durch die Lappen gehen.
> 
> > Das Handeln oder Verkaufen von Eiern im Forum oder über das Forum ist ebenfalls nicht gestattet.
> > Georgios Kipouros vom European Youth Forum appellierte dringlich, jetzt endlich zu handeln und nicht weiter nur über Onlinesicherheit von Kindern und Jugendlichen zu reden.

überarbeitet

2022-03-22 09:48 UTC, udomai commented
FPs sind weiterhin im Rule Editor – vielleicht muss nochmal ganz neu angesetzt werden? Kann der PR geschlossen werden?

2022-03-22 12:02 UTC, closed without merging