[de] KONNEKTOR_UMSO_UMSO
languagetool-org/languagetool pull request #6410
Opened 2022-03-04 18:22 UTC by St-ac-y

2022-03-07 13:49 UTC, St-ac-y commented
@udomai 
ready to merge

2022-03-07 16:21 UTC, udomai requested changes

2022-03-07 16:21 UTC, udomai commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +            </rule>
Was ist mit zweigliedrigen desto-Phrasen? Diese Regel findet z.B. das hier falsch:

> Je höher die Steuern auf Treibstoffe, desto höher der Druck auf den ÖPNV auszuweichen, desto höher aber auch die Belastung für einkommensschwächere Haushalte.

2022-03-07 16:21 UTC, udomai commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +            </rule>
Die Kombinatorik dieser Regel ließe sich übrigens mit `<or>` vereinfachen

2022-03-08 10:19 UTC, St-ac-y commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +            </rule>
Ich habe die Regel umgeschrieben und Regel 'je_je' mit 'umso_umso' zusammengeführt (damit wäre 'je_je' evtl. hinfällig)
Ist diese Lösung vielleicht effizienter? Dann kann kann alle extra Subrules für 'mehr' umgehen, da ja nicht genau klar ist, ob es weitere ADJ, die nicht mit KOM getaggt sind.

2022-03-09 12:09 UTC, St-ac-y commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +                <example>Je berühmter man wird, je erfolgreicher man wird und je mehr Geld man verdient, desto mehr unnötige Dinge kauft man.</example>
Überlege hier aus 2 Regeln 1 zu machen.

2022-03-10 14:33 UTC, udomai commented
@St-ac-y, den Bitte schließen, wenn er nicht mehr gemergt werden soll

2022-03-15 10:18 UTC, closed without merging