[de] WO_DRUM
languagetool-org/languagetool pull request #6411
Opened 2022-03-04 19:00 UTC by St-ac-y

2022-03-07 16:23 UTC, udomai requested changes

2022-03-08 10:49 UTC, St-ac-y commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +                        <token skip="-1">drauf</token>
Hier müsste ich ein bisschen nachdenken und überlegen, wie man wo als Adverbteil und wo als Relativpronomen unterscheiden kann.

2022-03-08 14:33 UTC, udomai commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +                        <token skip="-1">drauf</token>
Für den erwarteten Nutzen sollte hier nicht mehr zu viel Zeit reinfließen. Sackgassen notfalls links liegen lassen.

2022-03-10 11:34 UTC, St-ac-y commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +                        <token skip="-1">drauf</token>
evtl. für später... denke das nimmt dann doch mehr Zeit in Anspruch.

2022-03-10 14:35 UTC, closed without merging