[de] improve AN_FUER_SICH
languagetool-org/languagetool pull request #6462
Opened 2022-03-21 10:37 UTC by St-ac-y

Evtl. als Ergänzung für AN_FUER_SICH.

2022-03-22 09:45 UTC, udomai requested changes

2022-03-22 09:45 UTC, udomai commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +        <rulegroup id="AN_FUER_SICH" name="an für sich (an und für sich)" default="temp_off">
Ist die erste Subrule unverändert? Wenn eine Regel mal aktiv ist (und funktioniert), sollten wir sie nicht wieder temp_off machen. Wenn nur die zweite Subrule neu ist, sollte auch nur sie temp_off sein.

2022-03-22 11:44 UTC, St-ac-y commented on languagetool-language-modules/de/src/main/resources/org/languagetool/rules/de/grammar.xml
> +        <rulegroup id="AN_FUER_SICH" name="an für sich (an und für sich)" default="temp_off">
@udomai ok, erledigt.
Genau, die erste rule ist noch unverändert, aber man könnte die ändern, sodass sie sich allein auf die Rechtschreibung bezieht und dann diese rule hier als stylerule für Alternativen anhängen. Wenn das sinnvoll erscheint.

2022-03-28 14:32 UTC, udomai approved these changes

2022-03-28 14:32 UTC, merged