[be] Fix translations and mistakes. Add new rules
languagetool-org/languagetool pull request #8409
Opened 2023-05-05 22:45 UTC by PlagaMedicum

- Updated translations
- Added some rules in grammar
- Added ignore list
- Added Specific Case rule
- Added Simple Replace rule

2023-05-06 08:14 UTC, danielnaber requested changes

2023-05-06 08:14 UTC, danielnaber commented on languagetool-language-modules/be/src/main/java/org/languagetool/rules/be/BelarusianSpecificCaseRule.java
> + * @since 5.0
Could you update this to `6.2` please?

2023-05-06 08:14 UTC, danielnaber commented on languagetool-language-modules/be/src/main/java/org/languagetool/rules/be/BelarusianSpecificCaseRule.java
> +  public RuleMatch[] match(AnalyzedSentence sentence) {
This method seems to be duplicated and only the strings seem to be changed. Could you avoid the duplication?

2023-05-06 08:17 UTC, danielnaber requested changes

2023-05-06 08:17 UTC, danielnaber commented on languagetool-language-modules/be/src/main/java/org/languagetool/rules/be/SimpleReplaceRule.java
> +  addExamplePair(Example.wrong("<marker>З большага</marker>, гэта быў добры дзень."),
please fix the indentation here

2023-05-06 08:17 UTC, danielnaber commented on languagetool-language-modules/be/src/main/resources/org/languagetool/MessagesBundle_be.properties
>  ast = \u0410\u0441\u0442\u0443\u0440\u044b\u0439\u0441\u043a\u0430\u044f
Please do not change this file in git, it needs to be edited on webtranslateit.com

2023-05-23 21:15 UTC, PlagaMedicum commented
Fixed issues above. `BelarusianSpecificCaseRule.java` was rewritten accordant with the English version.

2023-05-23 21:32 UTC, danielnaber commented
Gtihub says "This branch cannot be rebased due to conflicts", could you update the PR?

2023-05-23 21:54 UTC, PlagaMedicum commented
Try it now

2023-05-23 21:59 UTC, danielnaber commented
Github still complains, see https://github.com/languagetool-org/languagetool/pull/8409

2023-05-23 22:03 UTC, PlagaMedicum commented on languagetool-language-modules/be/src/main/resources/org/languagetool/MessagesBundle_be.properties
It thinks that the file was modified, I guess

2023-05-23 22:27 UTC, PlagaMedicum commented on languagetool-language-modules/be/src/main/resources/org/languagetool/MessagesBundle_be.properties
I missed a new line character. Now everything should be fine, I hope it is fine now.
If it doesn't, how can I undo my commits on this file?

2023-05-24 07:18 UTC, merged

2023-05-24 07:20 UTC, danielnaber commented on languagetool-language-modules/be/src/main/resources/org/languagetool/MessagesBundle_be.properties
I've used a merge commit this time, it worked with that.