[pt-PT] Improved antipattern in rule ID:POSSESSIVE_WITHOUT_ARTICLE
languagetool-org/languagetool pull request #9376
Opened 2023-09-23 11:17 UTC by marcoagpinto

Heya, Susana and Pedro,

This enhancement fixes false positives that have been around for a very long time, and I should have done it before.

But it is better late, than never.

❤️ ❤️ ❤️ ❤️ ❤️

2023-09-23 14:27 UTC, marcoagpinto commented
And another antipattern for other rule (id:PARA-POR_TER_PARTICIPIO-PASSADO)

2023-09-25 07:57 UTC, p-goulart requested changes
This PR includes disparate changes to unrelated rules, IMO it should be split into multiple PRs.

---

We've finished our (Git documentation)[https://dev.languagetool.org/pt/git] for Portuguese-language contributors, do have a look, it might help guide you.

2023-09-25 07:57 UTC, p-goulart commented on languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
> +            <antipattern>
This antipattern technically allows for:
> o que você acha dos outros regras?
> quero dar mais consistência aos outros regras

Both of which are incorrect, so I don't think we should be introducing this.

---

The key word here is the **verb**. If you have a verb that governs a certain preposition (such as 'impor', in your example), then we should allow these constructions. I'd suggest adding an extra token accounting for this verb.

2023-09-25 07:57 UTC, p-goulart commented on languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
> +        <antipattern>
The key blocker of agreement here is the verb in the first-person singular, not the whole construction. I'd rethink this.

2023-09-25 07:57 UTC, p-goulart commented on languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/grammar.xml
> +          <token regexp='yes'>adoráv(el|eis)|amantes?|amig[ao]s?|car[ao]s?|clientes?|colaborador(es)?|colegas?|companheir[ao]s?|empregad[ao]s?|estimad[ao]s?|excelentes?|excelentíssim[ao]s?|filh[ao]s?
**[nitpick 🥜]** to avoid this type of thing, why not just a list of words with a POS tag filter for nouns/adjectives, and `inflected="yes"`?

2023-09-25 08:03 UTC, marcoagpinto commented
@p-goulart 

Sure, thanks for the feedback.

I will fix everything at night, and tomorrow morning you will see the new code.

2023-09-25 08:08 UTC, p-goulart commented
> I will fix everything at night, and tomorrow morning you will see the new code.

Sure, there's no rush. Just try to keep unrelated changes on different branches (and therefore PRs), because we could already have merged a couple of your changes! 😢

2023-09-25 08:14 UTC, marcoagpinto commented
> Sure, there's no rush. Just try to keep unrelated changes on different branches (and therefore PRs), because we could already have merged a couple of your changes! 😢

Ahhhh… sorry… I thought I should only do that for rules and for APs add all in the same branch.

We are always learning, I will do better.

2023-09-25 08:15 UTC, p-goulart commented
Aha, I understand your confusion. No, it's generally a better idea to keep everything separate. No worries, though, these APs should be easy enough to fix.

2023-09-25 17:05 UTC, marcoagpinto commented
@p-goulart 

Heya,

I believe I have resolved the issues.

Please have a look when you have the time.

Regarding the `“as unhas não pude arranjar”` I simply deleted the AP as I am too stressed to rethink the logic of it.

I simply made the changes you requested and did a `TESTRULES pt` and `TESTRULES pt-PT` to check if they broke anything.

From now on, I will create a branch for each rule and for each AP, this will make reviewing easier.

Thanks!

2023-09-25 17:34 UTC, p-goulart commented
> Regarding the `“as unhas não pude arranjar”` I simply deleted the AP as I am too stressed to rethink the logic of it.

My larger point here is that it is the 1SG inflection of the verb that makes that construction allowable. The fronting of the direct object is only incidental to that construction being incorrect. You can delete that rule, but we plan to do some larger work with agreement rules in the near future and I am pretty sure that we will greatly reduce the number of instances of 1SG verbs tagged.

---

> From now on, I will create a branch for each rule and for each AP, this will make reviewing easier.

I think you can keep antipatterns of the same rule within the same PR, no need to split them. Unless, of course, they are each massive and there's a high probability one of them will need more work.

2023-09-25 17:34 UTC, p-goulart approved these changes

2023-09-25 17:37 UTC, merged