GRPC length parameter for long sentences
languagetool-org/languagetool pull request #9403
Opened 2023-09-28 08:13 UTC by j-bolivar-lt

This configures a parameter called maxSentenceLength for long sentences to be handled in another way.

2023-09-28 08:57 UTC, SteVio89 commented on languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java
> + <pre>
Please do not push whitespace changes

2023-09-28 08:58 UTC, SteVio89 commented on languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java
> +import com.sun.xml.bind.v2.TODO;
This should not be necessary.

2023-09-28 09:04 UTC, fabrichter requested changes
Some small changes, then LGTM

2023-09-28 09:04 UTC, fabrichter commented on languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java
> +import com.sun.xml.bind.v2.TODO;
Please delete this

2023-09-28 09:04 UTC, fabrichter commented on languagetool-core/src/main/java/org/languagetool/rules/GRPCRule.java
> +  private final int maxSentenceLength = serviceConfiguration.getOptions().get("maxSentenceLength") == null ? Integer.MAX_VALUE : Integer.valueOf(serviceConfiguration.getOptions().get("maxSentenceLeng
Please move the initialization to the constructor, where other options are initialized.

2023-10-10 09:00 UTC, fabrichter approved these changes

2023-10-10 09:01 UTC, merged