[en] hyphenated compounds
languagetool-org/languagetool pull request #9526
Opened 2023-10-25 08:37 UTC by evan-defran-lt

2023-11-04 09:52 UTC, danielnaber commented
Could you add a test to `AbstractEnglishSpellerRuleTest`?

2023-11-07 11:29 UTC, evan-defran-lt commented
@danielnaber, just added a test. 
Java programming is new to me, so any feedback is greatly appreciated.

2023-11-07 15:43 UTC, danielnaber requested changes

2023-11-07 15:43 UTC, danielnaber commented on languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AbstractEnglishSpellerRule.java
> +            }
indentation is off here

2023-11-07 15:43 UTC, danielnaber commented on languagetool-language-modules/en/src/main/java/org/languagetool/rules/en/AbstractEnglishSpellerRule.java
> +      }
indentation if off here

2023-11-07 15:43 UTC, danielnaber commented on languagetool-language-modules/en/src/test/java/org/languagetool/rules/en/AbstractEnglishSpellerRuleTest.java
> +    assertFirstMatch("long-trem", "long-term");
Looks good!

2023-11-17 08:20 UTC, merged