[de] improve GermanSpellerRule + add Tests
languagetool-org/languagetool pull request #9585
Opened 2023-11-02 14:54 UTC by AgnesKleinhans

Accept compounds where the first part

- ends with `-mus` (`Mechanismuserstellung`), `-ss` (e.g. `Fitnesscoaching)`, or `-z` (e.g. `Anreizvergütungskoeffizienten`)  and is a noun
- ends with `-en` and is a plural noun (e.g. `Figurenerstellung`)

2023-11-04 10:05 UTC, danielnaber requested changes

2023-11-04 10:05 UTC, danielnaber commented on languagetool-language-modules/de/src/main/java/org/languagetool/rules/de/GermanSpellerRule.java
> +        (part1.matches(".*(mus|ss|z)") && isNoun(part2uc)) || isPluralNoun(part1) && part1.endsWith("en") &&
The logic conditions are difficult to read now, can we move parts of them to their own method or find a different solution to make them easier to read?

2023-11-04 10:05 UTC, danielnaber commented on languagetool-language-modules/de/src/test/java/org/languagetool/rules/de/GermanSpellerRuleTest.java
> +    assertTrue(rule.ignorePotentiallyMisspelledWord("Hospizgemeinschaft"));
Maybe add a comment here that "...z" + noun is a special case

2023-11-06 11:11 UTC, AgnesKleinhans commented
@danielnaber Could you review again? Thanks! :-)

2023-11-06 12:51 UTC, merged